services:
  api_gateway:
    build: ./http-api-gateway
    ports:
      - "3000:3000"
    volumes:
      - D:/yacine/dev/Learn/nestjs-microservices-tutorial/http-api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000

  users_microservice:
    build: ./user-microservice  
    volumes:
      - D:/yacine/dev/Learn/nestjs-microservices-tutorial/user-microservice/src:/usr/src/app/src  # Corrected path
    command: npm run start:dev

  payments_microservice:
    build: ./payments-microservice
    volumes:
      - D:/yacine/dev/Learn/nestjs-microservices-tutorial/payments-microservice/src:/usr/src/app/src
    command: npm run start:dev

  nats:
    image: nats
    ports:
      - 4222:4222
